<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="TestNGProject by groups" duration-ms="210" started-at="2019-09-06T22:52:42Z" finished-at="2019-09-06T22:52:42Z">
    <groups>
      <group name="smoke">
        <method signature="Testing3.mainTest()[pri:2, instance:selenium.Testing3@48eff760]" name="mainTest" class="selenium.Testing3"/>
      </group> <!-- smoke -->
      <group name="xyz">
        <method signature="Testing3.mainTest()[pri:2, instance:selenium.Testing3@48eff760]" name="mainTest" class="selenium.Testing3"/>
      </group> <!-- xyz -->
      <group name="chutiya">
        <method signature="Testing3.mainTest()[pri:2, instance:selenium.Testing3@48eff760]" name="mainTest" class="selenium.Testing3"/>
      </group> <!-- chutiya -->
    </groups>
    <test name="GRP-chutiya" duration-ms="210" started-at="2019-09-06T22:52:42Z" finished-at="2019-09-06T22:52:42Z">
      <class name="selenium.Testing3">
        <test-method status="PASS" signature="homeTest()[pri:1, instance:selenium.Testing3@48eff760]" name="homeTest" duration-ms="26" started-at="2019-09-06T18:52:42Z" finished-at="2019-09-06T18:52:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homeTest -->
        <test-method status="FAIL" signature="mainTest()[pri:2, instance:selenium.Testing3@48eff760]" name="mainTest" duration-ms="7" started-at="2019-09-06T18:52:42Z" depends-on-methods="selenium.Testing3.homeTest" finished-at="2019-09-06T18:52:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Verifying element expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying element expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at selenium.Testing3.mainTest(Testing3.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mainTest -->
      </class> <!-- selenium.Testing3 -->
    </test> <!-- GRP-chutiya -->
  </suite> <!-- TestNGProject by groups -->
</testng-results>
